### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@gmail.com",
  "locaiton": "East Hill",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "https://www.istockphoto.com/photo/surprised-baby-girl-wearing-heart-shaped-glasses-gm1294927798-388798069?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_top&utm_content=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fgirl&utm_term=girl%3A%3Asearch-aggressive-affiliates-v1%3Ab"
}

###USER SHOW
GET http://localhost:3000/users/3

###USER UPDATE
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
  "name": "Zia",
  "email": "zia@gmail.com"
}

###USER DESTROY
DELETE http://localhost:3000/users/1

###CATEGORY CREATE
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Test Category"
}

###CATEGORY SHOW
GET http://localhost:3000/categories/1

###POSTS INDEX
GET http://localhost:3000/posts

###POSTS CREATE
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUwMTIwOTV9.D-_TR0FciEBAXtoJ0E_JMyofTczQddXZf7PYZ26lKUE

{
  "title": "test title",
  "body": "test body",
  "image_url": "image.jpeg",
  "category_id": 2
}

###POSTS SHOW
GET http://localhost:3000/posts/1

###POSTS UPDATE
PATCH http://localhost:3000/posts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUwMTIwOTV9.D-_TR0FciEBAXtoJ0E_JMyofTczQddXZf7PYZ26lKUE

{
  "title": "update test",
  "body": "update test"
}

###POSTS DESTROY
DELETE http://localhost:3000/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUwMTIwOTV9.D-_TR0FciEBAXtoJ0E_JMyofTczQddXZf7PYZ26lKUE

###COMMENTS CREATE
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUwMTIwOTV9.D-_TR0FciEBAXtoJ0E_JMyofTczQddXZf7PYZ26lKUE

{
  "body": "test body",
  "image_url": "image.jpeg",
  "post_id": 1
}

###COMMENTS UPDATE
PATCH http://localhost:3000/comments/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUwMTIwOTV9.D-_TR0FciEBAXtoJ0E_JMyofTczQddXZf7PYZ26lKUE

{
  "body": "update comment test"
}

###DELETE COMMENT
DELETE http://localhost:3000/comments/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzUwMTU0MjN9.M-xx-ey8OFKHar8Q_JaF-zaCd3jV2N_7nGT1381oa5w


### Sessions create (login)

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "zia@gmail.com",
  "password": "password"
}