### SESSION CREATE

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "laura@gmail.com",
  "password": "password"
}

### USER CREATE
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@gmail.com",
  "location": "test location",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "testphoto.jpg"
}

###USER SHOW
GET http://localhost:3000/users/3

###USER UPDATE
PATCH http://localhost:3000/users/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzUxMTU2ODR9.DSbaBDrxGVgaRnEk7NCD5hp8gz_XvgyCazPgb4yi-Nw

{
  "name": "test update",
  "location": "south side"
}

###USER DESTROY
DELETE http://localhost:3000/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2MzUxMTU1MjJ9.9ys6XmNgu_mHomNzIK4Apwr_SlGr90abO3Rdwva-QFM

###CATEGORY CREATE
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Test Category"
}

###CATEGORY SHOW
GET http://localhost:3000/categories/1

###POSTS INDEX
GET http://localhost:3000/posts

###POSTS CREATE
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzUxMTU2ODR9.DSbaBDrxGVgaRnEk7NCD5hp8gz_XvgyCazPgb4yi-Nw

{
  "title": "test title",
  "body": "test body",
  "image_url": "image.jpeg",
  "category_id": 1
}

###POSTS SHOW
GET http://localhost:3000/posts/1

###POSTS UPDATE
PATCH http://localhost:3000/posts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzUxMTU2ODR9.DSbaBDrxGVgaRnEk7NCD5hp8gz_XvgyCazPgb4yi-Nw

{
  "title": "update test",
  "body": "update test"
}

###POSTS DESTROY
DELETE http://localhost:3000/posts/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2LCJleHAiOjE2MzUxMTU1MjJ9.9ys6XmNgu_mHomNzIK4Apwr_SlGr90abO3Rdwva-QFM

###COMMENTS CREATE
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer 

{
  "body": "comment comment comment",
  "image_url": "image.jpeg",
  "post_id": 1
}

###COMMENTS UPDATE
PATCH http://localhost:3000/comments/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUxMTYyMjl9.5Qw_qSAC8cKKVrVarOQsOzN-Nv_K33lcelTJOWoA4JA

{
  "body": "update comment test",
  "image_url": "testimageupdate.jpg"
}

###DELETE COMMENT
DELETE http://localhost:3000/comments/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUxMTYyMjl9.5Qw_qSAC8cKKVrVarOQsOzN-Nv_K33lcelTJOWoA4JA

###MEETUP INDEX
GET http://localhost:3000/meetups

###MEETUP CREATE
POST http://localhost:3000/meetups
Content-Type: application/json
Authorization: Bearer 

{
  "title": "test title",
  "location": "test location",
  "image_url": "image2.jpeg"
}

###MEETUP SHOW
GET http://localhost:3000/meetups/1

###MEETUP UPDATE
PATCH http://localhost:3000/meetups/2
Content-Type: application/json
Authorization: Bearer 

{
  "title": "update test",
  "location": "update test"
}

###MEETUP DESTROY
DELETE http://localhost:3000/meetups/2
Authorization: Bearer 

