@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDcxMTA3Mjh9.fp83HlkCX96isA51kMudH3RW1FMIK4rmoFqp3-yu8jE

### SESSION CREATE

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "zia@gmail.com",
  "password": "password"
}

### USER CREATE
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "bella",
  "email": "bella@gmail.com",
  "location": "Altoona, WI",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "https://images.pexels.com/photos/4276936/pexels-photo-4276936.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"
}

###USER SHOW
GET http://localhost:3000/users/1
Authorization: Bearer {{jwt}}

###USER UPDATE
PATCH http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "test update",
  "location": "south side"
}

###USER DESTROY
DELETE http://localhost:3000/users/me
Authorization: Bearer {{jwt}}

###CATEGORY index
GET http://localhost:3000/categories
Content-Type: application/json

###CATEGORY SHOW
GET http://localhost:3000/categories/1

###POSTS INDEX
GET http://localhost:3000/posts

###POSTS CREATE
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Bringing plants indoors for the winter",
  "body": "How to give them castile soap baths",
  "image_url": "image.jpeg",
  "category_id": 1
}

###POSTS SHOW
GET http://localhost:3000/posts/14

###POSTS UPDATE
PATCH http://localhost:3000/posts/14
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Beekeeping in Wisconsin"
}

###POSTS DESTROY
DELETE http://localhost:3000/posts/6
Authorization: Bearer {{jwt}}

###COMMENTS CREATE
POST http://localhost:3000/comments
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "body": "comment comment comment",
  "image_url": "image.jpeg",
  "post_id": 1
}

###COMMENTS UPDATE
PATCH http://localhost:3000/comments/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "body": "update comment test",
  "image_url": "testimageupdate.jpg"
}

###DELETE COMMENT
DELETE http://localhost:3000/comments/7
Authorization: Bearer {{jwt}}

###MEETUP INDEX
GET http://localhost:3000/meetups

###MEETUP CREATE
POST http://localhost:3000/meetups
Content-Type: application/json
Authorization: Bearer 

{
  "title": "test title",
  "location": "test location",
  "image_url": "image2.jpeg"
}

###MEETUP SHOW
GET http://localhost:3000/meetups/1

###MEETUP UPDATE
PATCH http://localhost:3000/meetups/2
Content-Type: application/json
Authorization: Bearer 

{
  "info": "Green pepper cranberry spritzer chai tea creamy cauliflower alfredo sauce naga viper portobello mushrooms figs green grapes kimchi alfalfa sprouts creamiest roasted brussel sprouts coconut sugar. Frosted gingerbread bites heat banana bread bite sized entree winter ginger carrot spiced juice red pepper peaches hummus falafel bowl eating together mint lime taco salsa strawberry spinach salad. Overflowing Sicilian pistachio pesto cauliflower spicy main course red grapes samosa appetizer mangos fiery fruit blueberry chia seed jam avocado basil pesto mediterranean avocado dressing drizzle peanut butter rich coconut cream. Bananas mocha chocolate spring peppermint double dark chocolate cherry bomb pepper grains Malaysian chocolate kale caesar salad strawberries parsley dessert potato."
}

###MEETUP DESTROY
DELETE http://localhost:3000/meetups/2
Authorization: Bearer 

