# User.create!([
#   {name: "Zia", email: "zia@gmail.com", password_digest: "$2a$12$p6aVt1lUOv/dqDKRuCe2lu3eW0elKzMAzrEyYL.x1nuqbYKv49M9C", location: "West Side", image_url: "https://images.unsplash.com/flagged/photo-1564756697507-6ec2d974ba64?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGJvc3RvbiUyMHRlcnJpZXJ8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60"},
#   {name: "Nigel", email: "nigel@gmail.com", password_digest: "$2a$12$0rqLpjtsWZ2sdpKPf0KnauN43/Dczkc6QR67CVTjE9MIyhF0lW8le", location: "South Side", image_url: "https://unsplash.com/photos/j7uVTlpwI0o"},
#   {name: "Elsie", email: "elsie@gmail.com", password_digest: "$2a$12$ui6CI22mUSRLSCz3dF5WXew3p.pOsGe8/CbZKyN/qAMfDnhWmG2QO", location: "East Side", image_url: "https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dGFiYnklMjBjYXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60"},
# ])

# Category.create!([
#   {name: "Plants"},
#   {name: "Bees"},
#   {name: "Perennial Flowers"}
# ])
# Category.create!([
#   {name: "Vegetables"},
#   {name: "Indoor Gardening"},
#   {name: "Butterflies"}
# ])

# Post.create!([
  # {title: "Planning Your Landscaping", body: "Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion daikon amaranth tatsoi tomatillo melon azuki bean garlic.

  # Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.
    
  # Turnip greens yarrow ricebean rutabaga endive cauliflower sea lettuce kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter purslane kale. Celery potato scallion desert raisin horseradish spinach carrot soko. Lotus root water spinach fennel kombu maize bamboo shoot green bean swiss chard seakale pumpkin onion chickpea gram corn pea. Brussels sprout coriander water chestnut gourd swiss chard wakame kohlrabi beetroot carrot watercress. Corn amaranth salsify bunya nuts nori azuki bean chickweed potato bell pepper artichoke.", user_id: 7, category_id: 4, image_url: "https://images.pexels.com/photos/242265/pexels-photo-242265.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"},
  # {title: "Easiest Vegetables to Grow", body: "Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery. Bunya nuts black-eyed pea prairie turnip leek lentil turnip greens parsnip. Sea lettuce lettuce water chestnut eggplant winter purslane fennel azuki bean earthnut pea sierra leone bologi leek soko chicory celtuce parsley jÃ­cama salsify.

  # Celery quandong swiss chard chicory earthnut pea potato. Salsify taro catsear garlic gram celery bitterleaf wattle seed collard greens nori. Grape wattle seed kombu beetroot horseradish carrot squash brussels sprout chard.
    
  # Pea horseradish azuki bean lettuce avocado asparagus okra. Kohlrabi radish okra azuki bean corn fava bean mustard tigernut jÃ­cama green bean celtuce collard greens avocado quandong fennel gumbo black-eyed pea. Grape silver beet watercress potato tigernut corn groundnut. Chickweed okra pea winter purslane coriander yarrow sweet pepper radish garlic brussels sprout groundnut summer purslane earthnut pea tomato spring onion azuki bean gourd. Gumbo kakadu plum komatsuna black-eyed pea green bean zucchini gourd winter purslane silver beet rock melon radish asparagus spinach.", user_id: 8, category_id: 4, image_url: "https://images.pexels.com/photos/7658811/pexels-photo-7658811.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"},
  # {title: "Growing Root Vegetables", body: "Pea horseradish azuki bean lettuce avocado asparagus okra. Kohlrabi radish okra azuki bean corn fava bean mustard tigernut jÃ­cama green bean celtuce collard greens avocado quandong fennel gumbo black-eyed pea. Grape silver beet watercress potato tigernut corn groundnut. Chickweed okra pea winter purslane coriander yarrow sweet pepper radish garlic brussels sprout groundnut summer purslane earthnut pea tomato spring onion azuki bean gourd. Gumbo kakadu plum komatsuna black-eyed pea green bean zucchini gourd winter purslane silver beet rock melon radish asparagus spinach.

  # Beetroot water spinach okra water chestnut ricebean pea catsear courgette summer purslane. Water spinach arugula pea tatsoi aubergine spring onion bush tomato kale radicchio turnip chicory salsify pea sprouts fava bean. Dandelion zucchini burdock yarrow chickpea dandelion sorrel courgette turnip greens tigernut soybean radish artichoke wattle seed endive groundnut broccoli arugula.
    
  # Soko radicchio bunya nuts gram dulse silver beet parsnip napa cabbage lotus root sea lettuce brussels sprout cabbage. Catsear cauliflower garbanzo yarrow salsify chicory garlic bell pepper napa cabbage lettuce tomato kale arugula melon sierra leone bologi rutabaga tigernut. Sea lettuce gumbo grape kale kombu cauliflower salsify kohlrabi okra sea lettuce broccoli celery lotus root carrot winter purslane turnip greens garlic. JÃ­cama garlic courgette coriander radicchio plantain scallion cauliflower fava bean desert raisin spring onion chicory bunya nuts. Sea lettuce water spinach gram fava bean leek dandelion silver beet eggplant bush tomato.", user_id: 8, category_id: 4, image_url: "https://images.pexels.com/photos/9301/healthy-vegetables-restaurant-nature.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500"},
  # {title: "Simple Garden to Table Meals", body: "Vitamin glow Thai super chili lemon tahini dressing green onions bento box cilantro lime vinaigrette strawberry mango smoothie lemon red lentil soup thyme strawberries asian pear Italian pepperoncini shiitake mushrooms second course falafel bites peanut butter blueberries sleepy morning tea udon noodles couscous cozy cinnamon oatmeal green tea lime banh mi salad rolls tabasco pepper cherries Thai basil curry Chinese five-spice powder. Coconut sugar fig arugula cashew salad paprika banana kale caesar salad overflowing raspberries peach strawberry mango sweet potato black bean burrito simmer.

  # Citrusy cashew banana bread tempeh almonds ultimate frosted gingerbread bites cool cucumbers earl grey latte eating together lingonberry samosa pinch of yum macadamia nut cookies red pepper tahini drizzle black beans sandwiches walnut mushroom tart hazelnut shiitake sweet potato pasta instant pot crunchy seaweed pumpkin. Chocolate peanut butter dip farro platter artichoke hearts rich coconut cream kale heat vegan double dark chocolate green papaya salad dessert butternut mix cherry fiery fruit ginger carrot spiced juice lentils hummus falafel bowl bite sized summer cozy butternut candy cane winter.
    
  # Lemongrass burritos peaches quinoa flatbread spring crumbled lentils red curry tofu noodles chili almond milk habanero golden roasted peanuts soba noodles sesame soba noodles tofu delightful blueberry scones dragon fruit Caribbean red habanero overflowing berries crunchy. Hemp seeds springtime strawberry Sicilian pistachio pesto Thai dragon pepper picnic salad kung pao pepper zesty tofu pad thai grapefruit Indian spiced apple vinaigrette chickpea crust pizza toasted hazelnuts blackberries shallots.", user_id: 1, category_id: 7, image_url: "https://images.pexels.com/photos/4969892/pexels-photo-4969892.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"}])
# Post.create!([
#   {title: "Fall Garden Prep", body: "Quodsi diceret no usu, prima epicuri ex nam. Vix ut dicit elitr, vivendo vituperata vituperatoribus no usu. Ne similique gloriatur vim, qui dico instructior intellegebat et, mei elit explicari ne. Eos in errem fabulas volutpat, mea ex autem civibus philosophia. Nec novum meliore deterruisset an, cu oporteat scriptorem eos.

#   Semper laoreet pericula sit no. Soluta volutpat expetenda per at, id dicit appareat mel. Novum causae an qui, ullum suscipit in eos, eam et unum nostrum blandit. Electram petentium id pri, nihil nonumes pro at. Ancillae insolens splendide an est.
    
#   Quo ut quodsi propriae. Tamquam consetetur scripserit mei eu, volumus accumsan iudicabit eam ne. Est ad impetus discere. Eum albucius tacimates euripidis ad. Eam ad simul argumentum, nullam feugait nostrum ei vel.", user_id: 1, category_id: 1, image_url: "https://images.unsplash.com/photo-1606840493062-47f440e8619c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZmFsbCUyMGxlYXZlc3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60"},
#   {title: "Edible Perennials", body: "Qui oratio maiorum at, id sint pertinax eos. Alii reque dicam ea mel. Eu vide sonet vim, ut harum accusata atomorum mei. Est saepe libris id, cu detracto voluptua vix, pri quot legere iudicabit id. Duo offendit placerat eu, eum amet esse maluisset cu.

#   Eu tota choro prompta pri, est illud voluptaria te. His sint posse an. Laudem corrumpit eu est. Sit torquatos assueverit ad. Feugait oporteat vis te, liber adipisci recusabo his cu. His tation epicuri ad, et numquam electram sententiae usu, vis iusto nullam mnesarchum ne.
    
#   Ad eum meliore feugait, ei vel laoreet appellantur, case ignota intellegebat mei eu. Ignota nostro minimum no est, eum errem quidam corpora te. Eos an paulo laoreet, facilisis efficiantur ad per, nam et libris postulant. Tota habeo instructior sea et, eum ea libris molestie. An ignota gloriatur signiferumque vel, cu ullum maiorum maiestatis vis, omnes tempor ridens ex pro.", user_id: 2, category_id: 3, image_url: "https://www.istockphoto.com/photo/green-asparagus-sticks-gm1084123600-290865967?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_top&utm_content=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fasparagus&utm_term=asparagus%3A%3Asearch-aggressive-affiliates-v1%3Ab"},
#   {title: "Bringing Plants Inside for Winter", body: "Malorum ornatus nominavi sit eu, te amet postulant laboramus est, iisque maiorum efficiendi ex pri. Ea duo ipsum quando, no alii aeterno docendi sea. Mel bonorum maluisset principes at, ad eam tale malorum comprehensam. His et dicat consequat, ut dolore primis deleniti mei, in maiestatis delicatissimi sit. Usu agam probo dissentiet ea, adhuc nostrud eum eu, brute feugiat mediocritatem at pro.

#   Nec ad omnes minimum liberavisse, accusamus splendide adipiscing est at, ne saperet constituto comprehensam mea. Ad nominavi splendide his, te aeque praesent usu, eam et quod salutandi. Et solum equidem sed, laboramus interpretaris vel no, per id elitr recusabo consectetuer. Id has nihil praesent complectitur, suas audiam dissentiunt ea quo, cu primis assentior instructior quo. Mel principes urbanitas adversarium cu, vim vidit solet tritani et, in putant adolescens adipiscing per.
    
#   Et wisi utamur nec. Mucius diceret ea nec, cu dolore soluta albucius eum, no postulant corrumpit percipitur quo. Ne omittam liberavisse mei, quot nominati te duo. In eos ferri constituam eloquentiam. Ne congue repudiare per, no accumsan suscipiantur pri.", user_id: 2, category_id: 1, image_url: "https://unsplash.com/photos/Cwgvz9u9YyA"},
#   {title: "Beekeeping in Wisconsin", body: "Ei inciderint accommodare necessitatibus cum. Ne eos sumo paulo essent. Ut tale scripta phaedrum eam. His illud praesent ad. Te fuisset necessitatibus quo, mutat signiferumque vim et.

#   Nec tempor definitionem ei, ne senserit voluptatum nam. Ad eam verterem pertinax patrioque, cu erant consetetur liberavisse cum, vis an iisque atomorum disputando. Odio etiam reformidans no sit. Ut alia volumus accumsan eum, assum phaedrum referrentur ea cum, an vel utamur bonorum scaevola.
    
#   Est facete verear erroribus in. His cibo doming tincidunt id. Nec an cibo voluptatum, pri justo detraxit ocurreret et, at ubique ocurreret sit. Cu vix nibh graeci, no pro modus noluisse argumentum. No error bonorum contentiones vis, id eam laoreet oporteat recusabo.", user_id: 1, category_id: 2, image_url: "https://www.istockphoto.com/photo/beekeeper-lifting-a-tray-out-of-a-beehive-gm178850019-25443982?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_top&utm_content=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fbeekeeping&utm_term=beekeeping%3A%3Asearch-aggressive-affiliates-v1%3Ab"}
# ])
# Post.create!([
#   {title: "Fall Garden Prep", body: "Quodsi diceret no usu, prima epicuri ex nam. Vix ut dicit elitr, vivendo vituperata vituperatoribus no usu. Ne similique gloriatur vim, qui dico instructior intellegebat et, mei elit explicari ne. Eos in errem fabulas volutpat, mea ex autem civibus philosophia. Nec novum meliore deterruisset an, cu oporteat scriptorem eos.

#   Semper laoreet pericula sit no. Soluta volutpat expetenda per at, id dicit appareat mel. Novum causae an qui, ullum suscipit in eos, eam et unum nostrum blandit. Electram petentium id pri, nihil nonumes pro at. Ancillae insolens splendide an est.
    
#   Quo ut quodsi propriae. Tamquam consetetur scripserit mei eu, volumus accumsan iudicabit eam ne. Est ad impetus discere. Eum albucius tacimates euripidis ad. Eam ad simul argumentum, nullam feugait nostrum ei vel.", user_id: 1, category_id: 1, image_url: "https://images.unsplash.com/photo-1606840493062-47f440e8619c?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8ZmFsbCUyMGxlYXZlc3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=400&q=60"},
#   {title: "Edible Perennials", body: "Qui oratio maiorum at, id sint pertinax eos. Alii reque dicam ea mel. Eu vide sonet vim, ut harum accusata atomorum mei. Est saepe libris id, cu detracto voluptua vix, pri quot legere iudicabit id. Duo offendit placerat eu, eum amet esse maluisset cu.

#   Eu tota choro prompta pri, est illud voluptaria te. His sint posse an. Laudem corrumpit eu est. Sit torquatos assueverit ad. Feugait oporteat vis te, liber adipisci recusabo his cu. His tation epicuri ad, et numquam electram sententiae usu, vis iusto nullam mnesarchum ne.
    
#   Ad eum meliore feugait, ei vel laoreet appellantur, case ignota intellegebat mei eu. Ignota nostro minimum no est, eum errem quidam corpora te. Eos an paulo laoreet, facilisis efficiantur ad per, nam et libris postulant. Tota habeo instructior sea et, eum ea libris molestie. An ignota gloriatur signiferumque vel, cu ullum maiorum maiestatis vis, omnes tempor ridens ex pro.", user_id: 2, category_id: 3, image_url: "https://www.istockphoto.com/photo/green-asparagus-sticks-gm1084123600-290865967?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_top&utm_content=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fasparagus&utm_term=asparagus%3A%3Asearch-aggressive-affiliates-v1%3Ab"},
#   {title: "Bringing Plants Inside for Winter", body: "Malorum ornatus nominavi sit eu, te amet postulant laboramus est, iisque maiorum efficiendi ex pri. Ea duo ipsum quando, no alii aeterno docendi sea. Mel bonorum maluisset principes at, ad eam tale malorum comprehensam. His et dicat consequat, ut dolore primis deleniti mei, in maiestatis delicatissimi sit. Usu agam probo dissentiet ea, adhuc nostrud eum eu, brute feugiat mediocritatem at pro.

#   Nec ad omnes minimum liberavisse, accusamus splendide adipiscing est at, ne saperet constituto comprehensam mea. Ad nominavi splendide his, te aeque praesent usu, eam et quod salutandi. Et solum equidem sed, laboramus interpretaris vel no, per id elitr recusabo consectetuer. Id has nihil praesent complectitur, suas audiam dissentiunt ea quo, cu primis assentior instructior quo. Mel principes urbanitas adversarium cu, vim vidit solet tritani et, in putant adolescens adipiscing per.
    
#   Et wisi utamur nec. Mucius diceret ea nec, cu dolore soluta albucius eum, no postulant corrumpit percipitur quo. Ne omittam liberavisse mei, quot nominati te duo. In eos ferri constituam eloquentiam. Ne congue repudiare per, no accumsan suscipiantur pri.", user_id: 2, category_id: 1, image_url: "https://unsplash.com/photos/Cwgvz9u9YyA"},
#   {title: "Beekeeping in Wisconsin", body: "Ei inciderint accommodare necessitatibus cum. Ne eos sumo paulo essent. Ut tale scripta phaedrum eam. His illud praesent ad. Te fuisset necessitatibus quo, mutat signiferumque vim et.

#   Nec tempor definitionem ei, ne senserit voluptatum nam. Ad eam verterem pertinax patrioque, cu erant consetetur liberavisse cum, vis an iisque atomorum disputando. Odio etiam reformidans no sit. Ut alia volumus accumsan eum, assum phaedrum referrentur ea cum, an vel utamur bonorum scaevola.
    
#   Est facete verear erroribus in. His cibo doming tincidunt id. Nec an cibo voluptatum, pri justo detraxit ocurreret et, at ubique ocurreret sit. Cu vix nibh graeci, no pro modus noluisse argumentum. No error bonorum contentiones vis, id eam laoreet oporteat recusabo.", user_id: 1, category_id: 2, image_url: "https://www.istockphoto.com/photo/beekeeper-lifting-a-tray-out-of-a-beehive-gm178850019-25443982?utm_source=unsplash&utm_medium=affiliate&utm_campaign=srp_photos_top&utm_content=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fbeekeeping&utm_term=beekeeping%3A%3Asearch-aggressive-affiliates-v1%3Ab"}
# ])
# Post.create!([
#   {title: "Building a Beekeeping Room", body: "There's us and there's them! Wait a minute! Do you ever get bored doing the same job every day? I see you also own Honeyburton and Honron! Yogi Bear, Fozzie Bear, Build-A-Bear. I'm not attracted to spiders. Ladies and gentlemen, there's no trickery here. Take away produce, that affects the entire animal kingdom. Don't move. Ooming in at you like a missile! Up the nose? If you don't move, he won't sting you. Roses are flowers! You wish you could. Welcome, New Hive Oity graduating class of... Montgomery. Honey really changes people. I'll leave now. Same way you did, I guess. It's OK, Lou. Order, please! You hear something? It's a bee law. You don't know what he's capable of feeling. I'm sorry. Flowers?! See? Oan you believe this is happening? Sorry. I guess he could have just gotten out of the way. ...get you something? Oute Bee, Golden Blossom, Ray Liotta Private Select? Bring the nose down. Bees have 100 percent employment, but we do jobs like taking the crud out. Well? Would you excuse me? Oh, my! It's a little grabby. Right. Hey, Honex! Breakfast is ready! Fruits, vegetables, they all need bees. I think something stinks in here! Montgomery's motion. I'm a florist from New York. The bee community is supporting you in this case, which will be the trial of the bee century. As always, watch your brooms, hockey sticks, dogs, birds, bears and bats. What in the name of Mighty Hercules is this? Has it been in your possession the entire time? The bees are back!", user_id: 1, category_id: 2, image_url: "https://images.unsplash.com/photo-1583673354352-9504815ae8e9?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YmVla2VlcGluZ3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60"},
#   {title: "How to Create a Bee Garden", body: "Pollen! Why would you question anything? I'm quite familiar with Mr. Oh, please. To the final Tournament of Roses parade in Pasadena. It goes under the mattresses. Wait a minute. I thought maybe you were remodeling. Oh, Barry. Some of them. Take him out. Is that another bee joke? Across the nation! But you can't! Mr. I was already a blood-sucking parasite. Oouple of newbies? Right. All right, we've got the sunflower patch in quadrant nine... If you do it well, it makes a big difference. I thought we were friends. I'm trying to lose a couple micrograms. Out where? It's the greatest thing in the world! We throw it in jars, slap a label on it, and it's pretty much pure profit. No one's flying the plane! Thank you. Our son, the stirrer! Wax monkey's always open. We are! It's a little grabby. Adam, don't! You got to think bee, Barry. So nice! I wonder where they were. there. I've never seen them this close. Turn off the radio. You pick it up. I've gotta go somewhere. Ladies and gentlemen of the jury, my grandmother was a simple woman. Have you ever been stung, Mr. It all depends on what 0900 means. Vanessa Bloome, FTD. At least you're out in the world. Huge and crazy. But you've never been a police officer, have you? I love it! I can't. Yes, sir!", user_id: 7, category_id: 2, image_url: "https://images.unsplash.com/photo-1515612402715-96a358304c50?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmVlJTIwZ2FyZGVufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60"},
#   {title: "Feeding Bees", body: "Not like a flower, but I like it. Oan't fly in rain. Spitting out your throw pillows! Flowers. We're not made of Jell-O. Yes. What did you want to show me? Oan't fly in rain. I hope that was all right. Vanessa, this is nothing more than a big metal bee. Those crazy legs kept me up all night. Bees make it. That girl was hot. I had to open my mouth and talk. Hang on. You got lint on your fuzz. Only to losing, son. Why do we do that? We're bees! Are they out celebrating? But isn't he your only hope? I was already a blood-sucking parasite. How did this get here? Don't waste it on a squirrel. What was that? Just a row of honey jars, as far as the eye could see. They know what it's like outside the hive. So long, bee! Making honey takes a lot of bees doing a lot of small jobs. Scared out of my shorts, check. That is diabolical. Of course. Exploiting tiny, helpless bees so you don't have to rehearse your part and learn your lines, sir? And now you'll start talking! Dumb bees! human. Are we going to be bees, orjust Museum of Natural History keychains? Uh-oh! Yes, sir! Why aren't you working? You know, I'm gonna guess bees. It's a bee law. Yeah, you do that. What's that? Across the nation! That concludes our ceremonies. Where you headed? Anyway... That's an insane choice to have to make. Oh, Barry...", user_id: 6, category_id: 2, image_url: "https://images.unsplash.com/photo-1498936178812-4b2e558d2937?ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8ZmVlZGluZyUyMGJlZXN8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60"},
#   {title: "Removing Hives", body: "Most bee jobs are small ones. Match point! Welcome, New Hive Oity graduating class of... It all depends on what 0900 means. You know, they have a Larry King in the human world too. We have Hivo, but it's a disease. He runs up the steps into the church. Yeah, me too. I can't believe I'm out! I know who makes it! Mooseblood's about to leave the building! Where is your proof? So, Mr. You did? Oh, this is so hard! A tri-county bee, Barry Benson, intends to sue the human race for stealing our honey, packaging it and profiting from it illegally! Poo water! Make out? She's... You know what this means? He's in the pool. Poo water! And a reminder for you rookies, bee law number one, absolutely no talking to humans! What? What is this place? But it's just a prance-about stage name! That's a conspiracy theory. What do you mean? I gotta say something. It's just coffee. Good. Montgomery is about out of ideas. Barry? No. Look at that. When I'm done with the humans, they won't be able to say, Honey I'm home, without paying a royalty! I wonder where they were. For all we know, he could be on steroids! I'll sting you, you step on me. Hey. It's just how I was raised. Smell it. How come you don't fly everywhere? I hear they put the roaches in motels. You keep bees. Who's your supplier? Would you like some honey with that? I love it! You think it was all a trap? Sorry.", user_id: 3, category_id: 2, image_url: "https://images.unsplash.com/photo-1511977688910-65315e4a57ac?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmVlJTIwc3dhcm18ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60"}
# ])

# Comment.create!([
#   {body: "Why does putting leaves over your garden help? What time of year should I start doing this?", post_id: 1, user_id: 3, image_url: nil},
#   {body: "Natursiums are my favorite! I'm not sure they're a perennial though.", post_id: 2, user_id: 3, image_url: "https://media.istockphoto.com/photos/nasturtium-picture-id636713072?b=1&k=20&m=636713072&s=170667a&w=0&h=qZXDmf1kg3zKvZKvB9ZQOrvojLk-3Rii0SCK1ts_49g="},
#   {body: "How do I harvest honey?", post_id: 2, user_id: 3, image_url: "https://unsplash.com/photos/YlXvFvfybaohttps://media.istockphoto.com/photos/inside-the-beehive-picture-id157311708?b=1&k=20&m=157311708&s=170667a&w=0&h=V8E8CD3aacxHVg3bKTw78xTyEQZt5L5eC-JyGNy2_LI="},
#   {body: "What happens to bees in the winter?", post_id: 4, user_id: 1, image_url: "https://media.istockphoto.com/photos/bee-hives-in-the-winter-organic-bee-farm-picture-id1217360093?b=1&k=20&m=1217360093&s=170667a&w=0&h=XJBD92nyURnuyEMhQMGNhCJlr4uafYFw4hA-1pXm3w0="}
# ])

# Meetup.create!([
#   {title: "What to Plant in Fall", location: "Pheonix Park", time: nil, image_url: nil},
#   {title: "Planting Perennials in the Fall", location: "Jeffers Rd Gardens", time: nil, image_url: "https://unsplash.com/photos/eL4ADAsiOR8"},
#   {title: "Beekeeping in Eau Claire", location: "Truax Garden", time: nil, image_url: "https://media.istockphoto.com/photos/bee-on-dandelion-picture-id94394792?b=1&k=20&m=94394792&s=170667a&w=0&h=9CsUhumKyjlJEPHLBVn5Uec0pniZED_0ynzyzAgUXco="},
# ])
Meetup.create!([
  {title: "Indoor Gardening", location: "Phoenix Park", time: 11/27/2021, image_url: "https://images.unsplash.com/photo-1573201106611-1de49dfada5d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aW5kb29yJTIwZ2FyZGVufGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60", info: "Strawberry mango smoothie mushroom risotto thyme basil coriander coconut homemade balsamic Thai basil curry appetizer cookies apples walnut mushroom tart Bolivian rainbow pepper miso dressing. Sleepy morning tea lemon lime minty portobello mushrooms red pepper double dark chocolate green onions spiced peppermint blast walnut pesto tart cherry cool simmer dragon fruit sweet potato black bean burrito mint lime taco salsa fiery fruit Thai super chili green bowl seeds red lentil curry. Cayenne chili salted tasty heat cilantro bananas pasta Bulgarian carrot cool off delightful blueberry scones vegan Southern Italian grapefruit tahini drizzle vitamin glow plums casserole kale.

  Mocha chocolate entree cherry bomb pepper pinch of yum creamy cauliflower alfredo garlic sriracha noodles chickpea crust pizza avocado chia seeds spicy sweet potato edamame hummus Italian linguine puttanesca blueberries crispy bite sized. Four-layer lemon red lentil soup hot couscous farro platter grenadillo naga viper salty chai tea Italian pepperoncini blood orange smash summertime mint black bean wraps peppermint peanut butter crunch peanut butter burritos crumbled lentils bento box crispy iceberg lettuce one bowl shallots." },
  {title: "Spring Planting", location: "Jeffers Rd Gardens", time: "2022-02-01T17:30:33.763Z", image_url: "https://images.unsplash.com/photo-1505235687559-28b5f54645b7?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cGxhbnQlMjBzcHJvdXR8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60", info: "Soybeans sweet corn hogs llamas or oink oink wind. Quack hammers eggplant is utters nails garden. Oranges cucumbers rhubarb gourds watermelon. Combine Harvester swather, baler as haybine parsley, melon in hay rake. Oranges cucumbers rhubarb gourds watermelon. Goose hammers cattle rats in crows. Oranges cucumbers rhubarb gourds watermelon. Turkey daisys eggs squeal, horses moonshine apples raising Mooo tractor plow. Pick up truck livestock, pet."},
  {title: "Winter Beekeeping", location: "Truax Garden", time: "2021-11-25T13:30:33.763Z", image_url: "https://images.unsplash.com/photo-1497322313607-9fa0c2c4c4f8?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8YmVlfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60", info: "You snap out of it! Buzzwell, we just passed three cups, and there's gallons more coming! Am I koo-koo-kachoo, or is this plane flying in an insect-like pattern? A little. Thinking bee! See that? OK. Mooseblood's about to leave the building! Stand to the side, kid. Vanessa, pull yourself together. Are you OK? What's the matter? One of them's yours! Italian Vogue. I'm sorry. Tell me where! This isn't so hard. The way we work may be a mystery to you. Hey. You're too late! Are you OK? Why? We're still here. Their wings are too small... These are winter boots. Drop it in, woman! Take away produce, that affects the entire animal kingdom. What was that? Where are you? Hey, Jocks! What about Bee Oolumbus? But bees know that every small job, if it's done well, means a lot. They'll never make it. Are there other bugs in your life? Would you like some honey with that? My mosquito associate will help you. Talking bee! Bye. 'They make the honey, and we make the money'? That's a bad job for a guy with a stinger. In tennis, you attack at the point of weakness! Get out of here, you creep! Spray him, Granny! And it's a perfect fit. Please clear the gate. You're dating a human florist! Does anyone onboard have flight experience? So nice! It's an allergic thing. What in the name of Mighty Hercules is this?
    "},
])
